name: Run Builds and Tests

on: [push, pull_request]

jobs:
  linux-build-latest:
    name: "Linux gcc-13"
    runs-on: ubuntu-24.04
    env:
      CC: gcc-13
      CXX: g++-13
    strategy:
      matrix:
        build-configuration: ['full', 'full (native)', 'core (non-monolithic)', 'core (C++20)']
    steps:
      - name: Install prerequisites
        run:  |
          sudo add-apt-repository 'deb http://mirrors.kernel.org/ubuntu jammy main universe'
          sudo apt-get update
          sudo apt-get install ninja-build
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout gdsb
        uses: actions/checkout@v4
        with:
          submodules: true